-- À exécuter dans Supabase SQL Editor. Ne jamais mettre une service_role key dans le frontend.
create extension if not exists pgcrypto;

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 80),
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 1 and 1000),
  published boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.page_visits (
  id bigint generated by default as identity primary key,
  session_id text not null check (session_id ~ '^[0-9a-fA-F-]{20,100}$'),
  visited_at timestamptz not null default now(),
  user_agent text check (char_length(coalesce(user_agent, '')) <= 500),
  referrer text check (char_length(coalesce(referrer, '')) <= 1000)
);
create index if not exists reviews_created_at_idx on public.reviews (created_at desc);
create index if not exists page_visits_visited_at_idx on public.page_visits (visited_at desc);

alter table public.reviews enable row level security;
alter table public.page_visits enable row level security;

drop policy if exists "Published reviews are public" on public.reviews;
create policy "Published reviews are public" on public.reviews for select using (published = true);
drop policy if exists "Users submit their own reviews" on public.reviews;
create policy "Users submit their own reviews" on public.reviews for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists "Admins moderate reviews" on public.reviews;
create policy "Admins moderate reviews" on public.reviews for all to authenticated
  using (lower(coalesce((select auth.jwt()->>'email'), '')) = 'carmelsindayihebura@gmail.com')
  with check (lower(coalesce((select auth.jwt()->>'email'), '')) = 'carmelsindayihebura@gmail.com');

drop policy if exists "Visitors record visits" on public.page_visits;
create policy "Visitors record visits" on public.page_visits for insert to anon, authenticated
  with check (session_id ~ '^[0-9a-fA-F-]{20,100}$');
drop policy if exists "Only admin reads visits" on public.page_visits;
create policy "Only admin reads visits" on public.page_visits for select to authenticated
  using (lower(coalesce((select auth.jwt()->>'email'), '')) = 'carmelsindayihebura@gmail.com');
